services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"                 
      - "--providers.docker=true"            
      - "--entrypoints.web.address=:80"     
      - "--entrypoints.websecure.address=:443" 
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web" 
      - "--certificatesresolvers.myresolver.acme.email=guellilmostafa@gmail.com" 
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ./letsencrypt:/letsencrypt 
    ports:
      - "80:80"
      - "443:443"
    labels:
    # Dashboard HTTP 
    - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.entrypoints=web"
    # Dashboard HTTPS 
    - "traefik.http.routers.api-secure.rule=Host(`traefik.localhost`)"
    - "traefik.http.routers.api-secure.service=api@internal"
    - "traefik.http.routers.api-secure.entrypoints=websecure"
    - "traefik.http.routers.api-secure.tls=true" 
    - "traefik.http.routers.api-secure.tls.certresolver=myresolver" 
    networks:
      - sre-network

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: sre-database
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql_root_password
    networks:
      - sre-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://web.localhost"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

  web:
    build: .
    container_name: web
    depends_on:
      - db
    ports:
      - "8080:80"
      - "443"
    labels:
      - "traefik.enable=true" # Enable Traefik my web container
      - "traefik.http.routers.web.rule=Host(`web.localhost`)" 
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.websecure.rule=Host(`web.localhost`)" 
      - "traefik.http.routers.websecure.entrypoints=websecure"
      - "traefik.http.routers.websecure.tls=true" # Enable TLS for HTTPS
      - "traefik.http.routers.websecure.tls.certresolver=myresolver" 
    networks:
      - sre-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "8081:80" 
    depends_on:
      - db
    secrets:
      - mysql_root_password
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.pma.rule=Host(`pma.localhost`)" 
      - "traefik.http.routers.pma.entrypoints=web" 
      - "traefik.http.routers.pma-secure.rule=Host(`pma.localhost`)" 
      - "traefik.http.routers.pma-secure.entrypoints=websecure" 
      - "traefik.http.routers.pma-secure.tls=true" 
      - "traefik.http.routers.pma-secure.tls.certresolver=myresolver" 
      - "traefik.http.services.pma.loadbalancer.server.port=80" 
    networks:
      - sre-network

volumes:
  db-data:
  letsencrypt:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password

networks:
  sre-network:
    driver: bridge
